language: python
python:
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install haf
script:
  - # or py.test for Python versions 3.5 and below
  - python -m haf run -c=./config.json